/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiRequest: typeof import('./src/components/ApiRequest.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PiniaStore: typeof import('./src/components/PiniaStore.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanLoading: typeof import('vant/es')['Loading']
    VantUi: typeof import('./src/components/VantUi.vue')['default']
    VueDirective: typeof import('./src/components/VueDirective.vue')['default']
  }
}
